CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(50) NOT NULL UNIQUE,
    password            VARCHAR(255) NOT NULL,
    role                VARCHAR(20) NOT NULL,
    is_default_password BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at       TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE projects (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100) NOT NULL,
    description         VARCHAR(255) NULL,
    project_key         VARCHAR(255) NOT NULL UNIQUE,
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE agent_config (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id          BIGINT NOT NULL,
    timezone            VARCHAR(255) NOT NULL,
    batch_size          BIGINT NOT NULL,
    flush_interval_sec  BIGINT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_project_agent_config_project UNIQUE (project_id),
    CONSTRAINT fk_project_agent_config_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE agent_config_sources (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_config_id     BIGINT NOT NULL,
    label               VARCHAR(100) NOT NULL,
    path                VARCHAR(500) NOT NULL,
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_pacs_config FOREIGN KEY (agent_config_id) REFERENCES agent_config(id) ON DELETE CASCADE,
    CONSTRAINT uq_pacs_config_label UNIQUE (agent_config_id, label)
);

CREATE TABLE agents (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id          BIGINT NOT NULL,
    agent_uuid          uuid NOT NULL UNIQUE,
    name                VARCHAR(150) NOT NULL,
    sequence            INTEGER NOT NULL,
    hostname            VARCHAR(255),
    os                  VARCHAR(100),
    os_version          VARCHAR(100),
    ip                  VARCHAR(45),
    status              VARCHAR(20) NOT NULL,
    last_seen_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_agents_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE agent_refresh_token (
     id                 BIGSERIAL PRIMARY KEY,
     agent_id           BIGINT NOT NULL,
     token_hash         VARCHAR(255) NOT NULL UNIQUE,
     expires_at         TIMESTAMP NOT NULL,
     status             VARCHAR(32) NOT NULL,
     created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

     CONSTRAINT fk_agent_refresh_token_agent FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
);

CREATE TABLE agent_access_history (
      id           BIGSERIAL PRIMARY KEY,
      ip           VARCHAR(45),
      hostname     VARCHAR(255),
      status       VARCHAR(20) NOT NULL,
      reason       TEXT,
      access_time  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);